Calculator Design
maury18/Math-Magicians pull request #2
Opened 2022-07-12 20:32 UTC by maury18

# This pull request is to check if the design of the calculator was added correctly as the requirements say
- Added components´ folder
- Added calculator.js file
- Imported calculator file into the App.js file
- Checked for linter errors
![image](https://user-images.githubusercontent.com/73630406/178589909-79f9e3dc-e779-4a40-afc5-92579cc14926.png)

2022-07-12 20:56 UTC, KDlamini requested changes
### Hi @maury18 🙋‍♀️,  

Great job so far! 💯 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 
✔️  Good PR description
✔️  Correct use of Gitflow 
✔️  Commit messages are meaningful
✔️  No linter errors

## Required Changes ♻️


**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-12 20:56 UTC, KDlamini commented on src/components/calculator.js
> +    <div className="app">
The `Calculator.js` component should be class-based as per project requirements.

![image](https://user-images.githubusercontent.com/38088818/178592870-5a16beff-f9cd-495f-a173-43c18f2ef3be.png)

- Kindly refactor your component to use classes.
For example:
```
import React, { Component } from 'react';

class Calculator extends Component {
  render() {
      ....
    };
  }
}

export default Calculator;
```

2022-07-12 20:56 UTC, KDlamini commented on src/App.js
>    return (
Same here, The `App.js` component should also be class-based. Kindly refactor your component to use classes as per project requirements.

2022-07-13 00:12 UTC, julie-ify approved these changes
Hi @maury18, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-13 14:28 UTC, merged